global using MultiTenancy.Contracts;
global using MultiTenancy.Models;
global using MultiTenancy.Settings;
global using MultiTenancy.Services;
global using MultiTenancy.Data;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using Microsoft.AspNetCore.Mvc;
global using MultiTenancy.Configurations;